config/routes.rb
Rails.application.routes.draw do
  resources :microposts

  resources :comments
  get '/login', to:'sessions#new'

  post '/login', to:'sessions#create'

  delete '/logout', to:'sessions#destroy'

  root 'static_pages#home'

  get '/help', to:'static_pages#help'

  get '/about', to:'static_pages#about'

  get  '/signup',  to: 'users#new'

  post '/signup',  to: 'users#create'

  resources :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments
  # default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :title, presence: true, length: {minimum: 6}
  validates :content, presence: true, length: {maximum: 255}
  validate :picture_size

  scope :load_data, -> {
    order(created_at: :desc)
  }

  scope :feed, ->(following_ids, id) {#truyen tham so vao
    where("user_id IN (?) OR user_id =?", following_ids, id)
  }

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
  def index
    @microposts = Micropost.load_data
  end

  def show
    @micropost = Micropost.find_by(id: params[:id])
    @comments = @micropost.comments
    @comment = Comment.new
  end

  def new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost Created!"
      redirect_to root_url
    else
      @feed_items=[]
      render 'static_pages/home'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :picture)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<!-- Blog Post -->

          <div class="panel panel-default">
            <!-- <img class="panel-img-top" src="<%=micropost.image_url%>" alt="panel image cap"> -->
              <%#= image_tag micropost.image_url, class: "panel-img-top" %>
            <div class="panel-body">
              <h2 class="panel-title">  <%= micropost.title %></h2>
              <p class="panel-text">  <%= micropost.content.html_safe %>
                  <%= image_tag micropost.picture.url if micropost.picture? %>
              </p>
                <%= link_to "Read More", micropost ,class: "btn btn-primary"%>
            </div>
            <div class="panel-footer text-muted">
                <span class="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago by <%= micropost.user.name %></span>
                  <%= link_to "delete", micropost, method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
          </div>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>

app/views/microposts/edit.html.erb
<h1>Microposts#edit</h1>
<p>Find me in app/views/microposts/edit.html.erb</p>

app/views/microposts/index.html.erb
<% provide(:title, 'Index') %>
<div class="container">

    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Microposts</h1>

          <%#= render partial: 'micropost', collection: @microposts, as: :micropost %>
          <%= render @microposts %>

          <!-- Pagination -->
          <ul class="pagination justify-content-center panel-default">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
          </ul>

         </div>
    </div>
</div>

app/views/microposts/new.html.erb
<h1>Microposts#new</h1>
<p>Find me in app/views/microposts/new.html.erb</p>

app/views/microposts/show.html.erb
<title>  <%= provide(:title,"Show") %></title>

    <!-- Page Content -->
    <div class="container micropost-show">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">  <%= @micropost.title %></h1>

          <!-- Author -->
          <p class="lead">
            by
              <%= link_to "#{@micropost.user.name}", user_url %>
          </p>

          <!-- Date/Time -->
          <small>  Posted <%= time_ago_in_words(@micropost.created_at) %> ago</small>

          <!-- Preview Image -->
          <!-- <img class="img-fluid rounded" src="<%=@micropost.image_url%>" alt="panel image cap"> -->

          <hr>

          <!-- Post Content -->
          <p class="lead">  <%= @micropost.content.html_safe %></p>

          <!-- <blockquote class="blockquote">
            <p class="mb-0">  <%#= @micropost.content %></p>
            <footer class="blockquote-footer">Written by
              <cite title="Source Title">  <%#= @micropost.user.name %></cite>
            </footer>
          </blockquote> -->
          <hr>

          <!-- Comments Form -->
          <div class="panel panel-default my-4">
            <h5 class="panel-header">Leave a Comment:</h5>
            <div class="panel-body">
                <%= form_for(@comment) do |f| %>
                <div class="field">
                  <%= f.text_area :content, placeholder: "Create New Comment..." %>
                </div>
                  <%= f.hidden_field :micropost_id ,value: @micropost.id %>
                  <%= f.submit "Create comment", class: "btn btn-primary" %>
            </div>
          </div>
  <% end %>
            <%= render @comments %>

        <!-- Sidebar Widgets Column -->
        <!-- <div class="col-md-4">

          <!-- Search Widget -->
          <!-- <div class="panel my-4">
            <h5 class="panel-header">Search</h5>
            <div class="panel-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div> -->

          <!-- Categories Widget -->
<!--           <div class="panel my-4">
            <h5 class="panel-header">Categories</h5>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

 -->          <!-- Side Widget -->
          <!-- <div class="panel my-4">
            <h5 class="panel-header">Side Widget</h5>
            <div class="panel-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 panel containers! -->
            <!-- </div>
          </div> -->

        <!-- </div>

      </div> -->
      <!-- /.row -->

    </div>
    <!-- /.container -->
<%# byebug %>

app/views/microposts/update.html.erb
<h1>Microposts#update</h1>
<p>Find me in app/views/microposts/update.html.erb</p>